apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-poc-helm.fullname" . }}
  labels:
    app: {{ include "rest-poc-helm.name" . }}
    helm.sh/chart: {{ include "rest-poc-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rest-poc-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9000
    protocol: TCP
